# Generated by Django 5.0.7 on 2024-11-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
